CREATE TABLE brew (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name VARCHAR NOT NULL DEFAULT '',
    style VARCHAR NOT NULL DEFAULT '',
    date DATE,
    batch INTEGER NOT NULL DEFAULT 1
)
